export const testDb = [
    {
        id: 0,
        name: 'Soup',
        description: 'A warm and comforting vegetable soup.',
        category: 'Перші страви',
        price: 10,
    },
    {
        id: 1,
        name: 'Pasta Carbonara',
        description: 'Classic Italian pasta with creamy sauce and bacon.',
        category: 'Другі страви',
        price: 15,
    },
    {
        id: 2,
        name: 'Grilled Chicken',
        description: 'Juicy chicken breast grilled to perfection.',
        category: 'Мʼясне',
        price: 20,
    },
    {
        id: 3,
        name: 'Caesar Salad',
        description: 'Crisp romaine lettuce with parmesan, croutons, and Caesar dressing.',
        category: 'Салати',
        price: 12,
    },
    {
        id: 4,
        name: 'Baguette',
        description: 'Freshly baked French baguette with a crispy crust.',
        category: 'Хліб & Булочки',
        price: 5,
    },
    {
        id: 5,
        name: 'Espresso',
        description: 'Rich and bold Italian coffee.',
        category: 'Напитки',
        price: 3,
    },
    {
        id: 6,
        name: 'Beef Stew',
        description: 'Slow-cooked beef with vegetables and herbs.',
        category: 'Мʼясне',
        price: 18,
    },
    {
        id: 7,
        name: 'Greek Salad',
        description: 'A mix of fresh vegetables, feta cheese, and olives.',
        category: 'Салати',
        price: 10,
    },
    {
        id: 8,
        name: 'Chocolate Croissant',
        description: 'Flaky croissant filled with rich chocolate.',
        category: 'Хліб & Булочки',
        price: 6,
    },
    {
        id: 9,
        name: 'Lemonade',
        description: 'Refreshing drink made with fresh lemons and mint.',
        category: 'Напитки',
        price: 4,
    },
    {
        id: 10,
        name: 'Tomato Soup',
        description: 'Creamy tomato soup with basil and croutons.',
        category: 'Перші страви',
        price: 9,
    },
    {
        id: 11,
        name: 'Risotto',
        description: 'Creamy mushroom risotto with parmesan.',
        category: 'Другі страви',
        price: 16,
    },
    {
        id: 12,
        name: 'Roast Beef',
        description: 'Tender roast beef with a side of mashed potatoes.',
        category: 'Мʼясне',
        price: 22,
    },
    {
        id: 13,
        name: 'Caprese Salad',
        description: 'Fresh tomatoes, mozzarella, and basil with olive oil.',
        category: 'Салати',
        price: 11,
    },
    {
        id: 14,
        name: 'Ciabatta Bread',
        description: 'Soft Italian bread perfect for sandwiches.',
        category: 'Хліб & Булочки',
        price: 7,
    },
    {
        id: 15,
        name: 'Cappuccino',
        description: 'Classic Italian coffee with steamed milk and foam.',
        category: 'Напитки',
        price: 4,
    },
    {
        id: 16,
        name: 'Minestrone',
        description: 'Hearty Italian vegetable soup with pasta.',
        category: 'Перші страви',
        price: 8,
    },
    {
        id: 17,
        name: 'Lasagna',
        description: 'Layered pasta with Мʼясне sauce, ricotta, and mozzarella.',
        category: 'Другі страви',
        price: 17,
    },
    {
        id: 18,
        name: 'Barbecue Ribs',
        description: 'Smoked ribs with barbecue sauce and coleslaw.',
        category: 'Мʼясне',
        price: 25,
    },
    {
        id: 19,
        name: 'Fruit Salad',
        description: 'A refreshing mix of seasonal fruits.',
        category: 'Салати',
        price: 9,
    },
    {
        id: 20,
        name: 'Garlic Bread',
        description: 'Toasted bread with garlic and butter.',
        category: 'Хліб & Булочки',
        price: 5,
    },
    {
        id: 21,
        name: 'Iced Tea',
        description: 'Chilled tea with a hint of lemon.',
        category: 'Напитки',
        price: 3,
    },
    {
        id: 22,
        name: 'Chicken Noodle Soup',
        description: 'Classic chicken soup with noodles and vegetables.',
        category: 'Перші страви',
        price: 9,
    },
    {
        id: 23,
        name: 'Stuffed Bell Peppers',
        description: 'Bell peppers filled with seasoned rice and beef.',
        category: 'Другі страви',
        price: 14,
    },
    {
        id: 24,
        name: 'Roast Lamb',
        description: 'Slow-cooked lamb with rosemary and garlic.',
        category: 'Мʼясне',
        price: 28,
    },
    {
        id: 25,
        name: 'Coleslaw',
        description: 'Crispy cabbage and carrot salad with creamy dressing.',
        category: 'Салати',
        price: 7,
    },
    {
        id: 26,
        name: 'Danish Pastry',
        description: 'Sweet pastry with fruit filling.',
        category: 'Хліб & Булочки',
        price: 6,
    },
    {
        id: 27,
        name: 'Hot Chocolate',
        description: 'Warm and creamy chocolate drink.',
        category: 'Напитки',
        price: 4,
    },
];
